
apiVersion: apps/v1
kind: Deployment
metadata:
  - name: java-app
    namespace: java
    labels:
      app: spring-boot-java

spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-java
  template:
    metadata:
      labels:
        app: spring-boot-java
    spec:
      containers:
        - name: spring-boot-container
          image: divya422/java-spring-boot:bcd6a2b0b7b5053fae905f4d63f7c288008bb55f
          ports:
            - containerPort: 8080
