apiVersion: v1
kind: Service
metadata:
    name: java-service-manifest
    namespace: java
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: spring-boot-java
